# Numpy Practice Notebook 

### Loading Library

In [1]:
import numpy as np

### 1. Converting array to list & list to array

In [2]:
# array from a python list

list1 = {2, 4, 6, 8, 10}
arr1 = np.array(list1)

In [3]:
arr1

array({2, 4, 6, 8, 10}, dtype=object)

In [4]:
list1

{2, 4, 6, 8, 10}

In [5]:
type(list1)

set

In [6]:
type(arr1)

numpy.ndarray

In [7]:
list2 = [[9 , 0 , 4 , 6],
         [4 , 6 , 2 , 1]]
arr2 = np.array(list2)

In [8]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [9]:
# float array

arr2 = np.array(list2, dtype = 'float')

In [10]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [11]:
arr3 = arr2.astype('int')

In [12]:
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [13]:
arr4 = np.array(list2, dtype = 'bool')

In [14]:
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
list2

[[9, 0, 4, 6], [4, 6, 2, 1]]

In [16]:
arr5 = np.array([2 , 5 , 2.0 , 'y'], dtype = 'object')

In [17]:
arr5

array([2, 5, 2.0, 'y'], dtype=object)

In [18]:
list3 = arr5.tolist()

In [19]:
list3

[2, 5, 2.0, 'y']

In [20]:
type(arr5)

numpy.ndarray

In [21]:
type(list3)

list

### 2. Array Dimensions

In [22]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [23]:
arr2.shape
#(row,clumn)

(2, 4)

In [24]:
arr2.size

8

In [25]:
arr2.dtype

dtype('float64')

In [26]:
arr2.ndim

2

### 3. Reversing Rows & Columns

In [27]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [28]:
arr2[::-1]
# reversing rows

array([[4., 6., 2., 1.],
       [9., 0., 4., 6.]])

In [29]:
arr2[::-1, ::-1]
# reversing columns

array([[1., 2., 6., 4.],
       [6., 4., 0., 9.]])

### 4. Specific Element Extraction

In [30]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [31]:
arr2[0, :]
# Extraacting 1st (0index) row elements

array([9., 0., 4., 6.])

In [32]:
arr2[:1, :]
# Extracting elements of 1st row, all columns

array([[9., 0., 4., 6.]])

In [33]:
arr2[:2, :]
# Extracting elements of 1st row & 2nd row, all columns

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [34]:
arr2[:-1, :]
# Extracting all rows except the last row

array([[9., 0., 4., 6.]])

In [35]:
arr2[:, 3]
# Extracting elements of all rows from the 4th column (3rd index)

array([6., 1.])

In [36]:
arr2[: , -1]
# Extracting elements of last column

array([6., 1.])

In [37]:
arr2[:, 1:3]
# Extracting all columns from column index 1 till before column index 3.  

array([[0., 4.],
       [6., 2.]])

In [38]:
arr2[1,:]
# Extracting the 2nd row (.i.e. 1st index) with all columns, 

array([4., 6., 2., 1.])

### 5. Basic Statistics

In [39]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [40]:
arr2.min()
# function for finding the minimum value in an array

0.0

In [41]:
arr2.max()
# function for finding the maximum value in an array

9.0

In [42]:
arr2.sum()
# function for finding the sum of all elements in an array

32.0

In [43]:
arr2.mean()
# function for finding the mean of all the values in an array

4.0

In [44]:
np.median(arr2)
# function for finding the median of all the values in an array

4.0

In [45]:
np.average(arr2)
# function for finding the average of all the values in an array

4.0

In [46]:
np.var(arr2)

7.75

### 6. Reshaping and Flattening

In [47]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [48]:
arr2.shape
# Function to find the current shape .i.e. no. of rows and columns in an array

(2, 4)

In [49]:
arr2.reshape(4,2)
# arrName.reshape(desired rows,desired columns)
# function to reshape the array to desired numbers of rows and columns.

array([[9., 0.],
       [4., 6.],
       [4., 6.],
       [2., 1.]])

In [50]:
arr2.reshape(1,8)

array([[9., 0., 4., 6., 4., 6., 2., 1.]])

In [51]:
arr2.reshape(8,1)

array([[9.],
       [0.],
       [4.],
       [6.],
       [4.],
       [6.],
       [2.],
       [1.]])

In [52]:
arr2

array([[9., 0., 4., 6.],
       [4., 6., 2., 1.]])

In [53]:
f1 = arr2.flatten()
# newArray = OldArray.flatten()
# flatten helps in reshaping any multidimensional array into a strict One-Dimensional Array

In [54]:
f1

array([9., 0., 4., 6., 4., 6., 2., 1.])

arr2 which was previously 2 X 4 is now converted into a One Dimensional Array : 1 X 8

In [55]:
arr2.ndim
# finding the dimension of arr2

2

In [56]:
f1.ndim
# finding the dimension of f1 (flattened array); just to confirm

1

### 7. Creating Random Arrays and Sequences

np.arange()

In [57]:
np.arange(10)
# np.arange(no.of elements wanted)
# Creating a random array starting from index 0 to index 9 .i.e 10 elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(2, 10)
# np.arange(element to start with, element to end before)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.arange(0, 10, 2)
#np.arange(element to start with, element to end before, step size or difference b/w consecutive elements)

array([0, 2, 4, 6, 8])

In [63]:
np.arange(10 , 0, -1)
# descending order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

np.linspace()

In [65]:
np.linspace(1,10,3)
# np.linspace(element to start from, element to end with, no.of total elements)
# stepsize or difference b/w the elements is automatically calculated and is equal to one another.

array([ 1. ,  5.5, 10. ])

In [66]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

npzeros()

In [73]:
np.zeros([3,2])
# np.zeros([rows, columns])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [75]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 8. Unique Items and Count

In [76]:
arr = [[1, 4, 5, 2, 2, 5],
       [4, 4, 1, 7, 4, 5]]

In [77]:
arr

[[1, 4, 5, 2, 2, 5], [4, 4, 1, 7, 4, 5]]

In [86]:
u_val
# function to find the unique elements in an array

array([1, 2, 4, 5, 7])

In [82]:
count = np.unique(arr, return_counts = True)
# function to count the ni. of times each unique element has appeared in the array

In [80]:
count
# below output shows that 1 is there 2times, 2 is there 2times, 4 is there 4 times, 5 is there 3 times, 7 is there is 1 times

array([2, 2, 4, 3, 1], dtype=int64)